flags: {}
packages:
  - '.'
  - location: subhask
    extra-dep: true
extra-deps:
  - hmatrix-nipals-0.2
  - tokenize-0.3.0
  - cassava-0.4.3.1
  - gamma-0.9.0.2
  - continued-fractions-0.9.1.1
  - converge-0.1.0.1
  - optparse-generic-1.1.0
resolver: lts-3.3
